### ISSUE TITLE
v 4.1 not working in a TypeScript project

### ISSUE THREAD

**Issue by kachkaev** [brummelte/sleep-promise#8]
Hi again @brummelte and thanks for your efforts to move the project to the next level!

I'm writing to report that `sleep-promise` v4.1 does not work in a TypeScript project. This is because Node still imports a js file rather than an `mjs`, but that file does not have a `default` export. Now the library is not usable because when I type `import * as sleep from "sleep-promise"`, I get a TypeScript compiler error, expectedly coming from [`index.d.ts`](https://github.com/brummelte/sleep-promise/blob/9b0dfecbb1167c44775dd6a6096454d4486cf82b/lib/index.d.ts), but when I try `import sleep as "sleep-promise"` and get cool TS hints, this exception shows up:

```
TypeError: sleep_promise_1.default is not a function
```

I guess you'll need to export `sleep` function twice to make `bundle.js` compatible with both `require` and `import`:

```js
module.exports = sleep;
module.exports.default = module.exports;
```
This is [what `chalk` does](https://github.com/chalk/chalk/blob/678152cf1952f3afe1e523a306c0413ad57c34b3/index.js#L228) at least, but they are implementing both flavours of exports manually. Given that your source is in es6 now, perhaps, there is some rollup option that would do the trick?

Rolling back to v2 for now 😉

**Comment by brummelte** [comment]
Tools like webpack support the "module" notation in package.json. So using TypeScript with webpack might work and use the esm-file. I've added type definitions for the esm-file. But I'm not sure if they will be loaded correctly. It seems like you can only define one entry file for types.

I can't seem to get TypeScript (without webpack) to work with the module syntax anyway. The following doesn't seem to work:
```js
import sleep from 'sleep-promise/build/esm';
```

And I don't want to add a default export to the common js bundle. So I've reverted the types.

You now will have to import it as `import * as sleep …` with TypeScript. Adding `--allowSyntheticDefaultImport` might also work to get TypeScript to accept a default export.

I'm closing this for now, because this has cost me too much time already.

If anybody finds a way of adding default import compatibility for TypeScript without changing the commonJS file, I'm happy to take a look again.

**Comment by kachkaev** [comment]
Thank you @brummelte! One final minor bit: could you please add `!types/*` to `.npmignore`? Otherwise, type definition files are not published and we're going back to https://github.com/brummelte/sleep-promise/issues/6#issue-311992224 😅

**Comment by brummelte** [comment]
Sorry :-)

`!types/*` not being added is correct. The path in package.json was wrong. Fixed now.

**Comment by kachkaev** [comment]
All works like a charm now! 😍  Many thanks for your time @brummelte!!!

**Comment by abel-mak** [comment]
> You now will have to import it as import * as sleep … with TypeScript.
Hi @brummelte, shouldn't the README be updated accordingly

**Comment by brummelte** [comment]
@abel-mak it's only for TypeScript. If you can find a way to make TypeScript work with the default import, I'm happy to change it.

**Comment by abel-mak** [comment]
@brummelte i see, thanks responding!
